Write to file
pwnesia/dnstake pull request #8
Opened 2022-01-14 11:00 UTC by indigo-sadland

Added cmd option that allows to save output to a file.

2022-01-14 13:02 UTC, dwisiswant0 requested changes

2022-01-14 13:02 UTC, dwisiswant0 commented on internal/executor/executor.go
> +	"sync"
Revert the order of importing packages like the previous one.

2022-01-14 13:02 UTC, dwisiswant0 commented on internal/executor/executor.go
> +		out += fmt.Sprintf("[%s] %s: %s", aurora.Red("ERR"), hostname, err.Error())
DO NOT save the error to a file, leave it on `stderr` with `gologger.Error()`.

2022-01-14 13:02 UTC, dwisiswant0 commented on internal/option/const.go
> +  -o, --output                Define path where you want to store the tool's output
```diff
-  -o, --output                Define path where you want to store the tool's output
+  -o, --output <FILE>         Save vulnerable hosts to FILE
```

2022-01-14 13:02 UTC, dwisiswant0 commented on internal/option/options.go
> +	Output			string
Use space indentation instead of tabs.

2022-01-14 14:03 UTC, indigo-sadland reviewed
I hope now all is done in the proper way!

2022-01-15 13:37 UTC, dwisiswant0 commented on internal/executor/executor.go
> +
Remove this trailing newline.

2022-01-15 13:51 UTC, dwisiswant0 approved these changes
Thanks for your contributions, @indigo-sadland! Merging now.

2022-01-15 13:52 UTC, merged